# nixpacks.toml

[phases.setup]
# These are the system packages required by Puppeteer to run Chrome
pkgs = [
  "chromium",
  "libgobject-2_0-0",
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxcomposite1",
  "libxcursor1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxrender1",
  "libxss1",
  "libxtst6",
  "libatk-1_0-0",
  "libatk-bridge-2_0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libnspr4",
  "libnss3",
  "libasound2",
  "libpangocairo-1_0-0",
  "libpango-1_0-0",
  "libcairo2",
  "libharfbuzz0b",
  "libfontconfig1",
  "libfreetype6"
]
